version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.12.1
    container_name: saia-rag-qdrant-dev
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6333/readyz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - saia-rag-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saia-rag-api-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - ENVIRONMENT=development
      - QDRANT_URL=http://qdrant:6333
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TENANT_ID=${TENANT_ID:-t_customerA}
    depends_on:
      - qdrant
    networks:
      - saia-rag-network
    restart: unless-stopped
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  qdrant_data:
    driver: local

networks:
  saia-rag-network:
    driver: bridge
