version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.12.1
    container_name: saia-rag-qdrant-prod
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6333/readyz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - saia-rag-network
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saia-rag-api-prod
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    environment:
      - ENVIRONMENT=production
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - qdrant
    networks:
      - saia-rag-network
    restart: unless-stopped
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  caddy:
    image: caddy:2.7-alpine
    container_name: saia-rag-caddy-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
    networks:
      - saia-rag-network
    restart: unless-stopped

volumes:
  qdrant_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local

networks:
  saia-rag-network:
    driver: bridge
